-- SCHEMA CREATION
CREATE SCHEMA `cohort-1_pod-1`;

-- TABLES CREATION
CREATE TABLE `borrower_details` (
  `BORROWER_ID` int NOT NULL AUTO_INCREMENT,
  `BORROWER_FULL_NAME` varchar(225) DEFAULT NULL,
  `BORROWER_CONTACT` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `CREATED_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BORROWER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `loan_details` (
  `LOAN_ID` int NOT NULL AUTO_INCREMENT,
  `LOAN_AMOUNT` BIGINT NOT NULL,
  `LOAN_TENURE` int NOT NULL,
  `BORROWER_ID` int NOT NULL,
  `LOAN_INTEREST` float DEFAULT NULL,
  `LOAN_NUMBER` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`LOAN_ID`),
  KEY `B_idx` (`BORROWER_ID`),
  CONSTRAINT `BORROWER_FK` FOREIGN KEY (`BORROWER_ID`) REFERENCES `borrower_details` (`BORROWER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

 
CREATE TABLE `user_details` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(255) DEFAULT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `USER_ROLE` varchar(255) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_EMAIL_UNIQUE` (`USER_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;